variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: quantumtinkerer/research

## Documentation for the format of this file can be found here:
## https://docs.gitlab.com/ce/ci/yaml/README.html#configuration-of-your-builds-with-gitlab-ci-yml

test minimal requirements:
  script:
    - conda env create -f environment-minimal.yml
    - source activate qsymm-minimal
    - py.test qsymm/ --cov=qsymm --verbose --cov-report term
  stage: test

test latest requirements:
  script:
    - conda env create -f environment-latest.yml
    - source activate qsymm-latest
    - py.test qsymm/ --cov=qsymm --verbose --cov-report term
  stage: test
